site_name: Swarms Docs
plugins:
  - glightbox
  - search
copyright: "&copy; Swarms, Inc."
extra_css:
  - docs/assets/css/extra.css
extra:
  # analytics:
  #   provider: google
  #   property: G-QM8EDPSCB6
  social:
    - icon: fontawesome/solid/house
      link: https://github.com/kyegomez/swarms/blob/master/images/swarmsbanner.png
    - icon: fontawesome/brands/discord
      link: https://discord.gg/qUtxnK2NMf
    - icon: fontawesome/brands/github
      link: https://github.com/kyegomez/Swarms/
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/Swarms/
theme:
    name: material
    custom_dir: docs/overrides
    logo: docs/assets/img/swarmsbanner.png
    palette:
      # Palette toggle for light mode
    - scheme: default
      primary: black
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    features:
        - content.code.copy
        - content.code.annotate
        - navigation.tabs
        - navigation.sections
        - navigation.expand
        - navigation.top
        - announce.dismiss
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
  - tables
  - def_list
  - footnotes
nav:
- Home:
    - Overview: "index.md"
    - Contributing: "contributing.md"
    - FAQ: "faq.md"
- Swarms Framework:
  - Overview: "swarmsk/index.md"
  - Structures:
    - Pipelines: "swarmsk/structures/pipelines.md"
    - Agents: "swarmsk/structures/agents.md"
    - Workflows: "swarmsk/structures/workflows.md"
    - Prompt Drivers: "swarmsk/structures/prompt-drivers.md"
    - Conversation Memory: "swarmsk/structures/conversation-memory.md"
    - Rulesets: "swarmsk/structures/rulesets.md"
    - Events: "swarmsk/structures/events.md"
  - Tools:
      - Overview: "swarmsk/tools/index.md"
      - Tool Memory: "swarmsk/tools/tool-memory.md"
      - Building Custom Tools: "swarmsk/tools/custom-tools.md"
  - Data:
    - Overview: "swarmsk/data/index.md"
    - Artifacts: "swarmsk/data/artifacts.md"
    - Embeddings: "swarmsk/data/embeddings.md"
    - Chunkers: "swarmsk/data/chunkers.md"
    - Loaders: "swarmsk/data/loaders.md"
    - Query Engines: "swarmsk/data/query-engines.md"
    - Summary Engines: "swarmsk/data/summary-engines.md"
    - Vector Stores: "swarmsk/data/vector-stores.md"
    - SQL Drivers: "swarmsk/data/sql-drivers.md"
- Swarms Tools:
    - Overview: "Swarms-tools/index.md"
    - Official Tools:
      - AwsIamClient: "Swarms-tools/official-tools/aws-iam-client.md"
      - AwsS3Client: "Swarms-tools/official-tools/aws-s3-client.md"
      - Calculator: "Swarms-tools/official-tools/calculator.md"
      - Computer: "Swarms-tools/official-tools/computer.md"
      - DateTime: "Swarms-tools/official-tools/date-time.md"
      - EmailClient: "Swarms-tools/official-tools/email-client.md"
      - FileManager: "Swarms-tools/official-tools/file-manager.md"
      - RestApiClient: "Swarms-tools/official-tools/rest-api-client.md"
      - SqlClient: "Swarms-tools/official-tools/sql-client.md"
      - ToolOutputProcessor: "Swarms-tools/official-tools/tool-output-processor.md"
      - KnowledgeBaseClient: "Swarms-tools/official-tools/knowledge-base-client.md"
      - WebScraper: "Swarms-tools/official-tools/web-scraper.md"
      - WebSearch: "Swarms-tools/official-tools/web-search.md"
- Examples:
    - Overview: "examples/index.md"
    - Agents:
      - Talk to Redshift: "examples/talk-to-redshift.md"
      - Talk to a Webpage: "examples/talk-to-a-webpage.md"
      - Talk to a PDF: "examples/talk-to-a-pdf.md"
    - Data:
      - Load and Query Pinecone: "examples/load-and-query-pinecone.md"
      - Load and Query Marqo: "examples/load-query-and-chat-marqo.md"
      - Query a Webpage: "examples/query-webpage.md"
    - Misc:
        - Count Tokens: "examples/count-tokens.md"
        - Using Text Generation Web UI: "examples/using-text-generation-web-ui.md"
        - Storing Conversation Memory in DynamoDB: "examples/store-conversation-memory-in-dynamodb.md"